# Generated by Django 4.1 on 2022-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('art', models.ImageField(upload_to='static/')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
